# Generated by Django 3.2.16 on 2022-12-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles_id',
            field=models.ForeignKey(blank=True, help_text='Выберите должность сотрудника', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.roles', verbose_name='Должность сотрудника'),
        ),
    ]
