# Generated by Django 3.2.16 on 2022-12-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_roles_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
