# Generated by Django 3.2.16 on 2022-12-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo_company',
            field=models.ImageField(blank=True, help_text='Выберите изображение', null=True, upload_to='media/', verbose_name='Лого компании'),
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
