# Generated by Django 3.2.16 on 2022-12-07 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221207_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='user_id',
            field=models.ForeignKey(help_text='Выберите клиента', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
