# Generated by Django 3.2.16 on 2022-12-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sale_compos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_supply', models.DateTimeField(help_text='Введите дату и время поставки', verbose_name='Дата и время поставки')),
                ('shipper_id', models.ForeignKey(help_text='Выберите поставщика', on_delete=django.db.models.deletion.CASCADE, to='main.shipper', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
    ]
