# Generated by Django 3.2.16 on 2022-12-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply_compos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_supply', models.IntegerField(help_text='Введите количество, шт.', verbose_name='Количество, шт.')),
                ('med_id', models.ForeignKey(help_text='Выберите лекарство', on_delete=django.db.models.deletion.CASCADE, to='main.med', verbose_name='Лекарство')),
                ('supply_id', models.ForeignKey(help_text='Выберите дату поставки', on_delete=django.db.models.deletion.CASCADE, to='main.supply', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставок',
            },
        ),
    ]
