# Generated by Django 3.2.16 on 2022-12-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_supply_compos'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='med_photo',
            field=models.ImageField(blank=True, help_text='Выберите изображение', null=True, upload_to='media/', verbose_name='Фото лекарства'),
        ),
    ]
