# Generated by Django 3.2.16 on 2022-12-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_user_adress_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress_id',
            field=models.ForeignKey(default=1, help_text='Выберите адрес', on_delete=django.db.models.deletion.CASCADE, to='main.adress', verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
