# Generated by Django 3.2.16 on 2022-12-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_user_adress_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress_id',
        ),
        migrations.AddField(
            model_name='user',
            name='adress_id',
            field=models.ManyToManyField(default='1', help_text='Выберите адрес', to='main.Adress', verbose_name='Адрес'),
        ),
    ]
