# Generated by Django 3.2.16 on 2022-12-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20221217_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress_id',
        ),
        migrations.AlterField(
            model_name='sale_compos',
            name='sale_id',
            field=models.ForeignKey(blank=True, help_text='Выберите дату продажи', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sale', verbose_name='Продажа'),
        ),
    ]
