# Generated by Django 3.2.16 on 2022-12-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20221217_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress_id',
            field=models.ForeignKey(default=1, help_text='Выберите адрес', on_delete=django.db.models.deletion.CASCADE, to='main.adress', verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale_compos',
            name='sale_id',
            field=models.ForeignKey(default=1, help_text='Выберите дату продажи', on_delete=django.db.models.deletion.CASCADE, to='main.sale', verbose_name='Продажа'),
            preserve_default=False,
        ),
    ]
