# Generated by Django 3.2.16 on 2022-12-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20221217_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logo_company',
        ),
    ]
