# Generated by Django 3.2.16 on 2022-12-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20221219_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_compos',
            name='recept_photo',
            field=models.ImageField(blank=True, help_text='Выберите изображение', null=True, upload_to='img/', verbose_name='Фото рецепта'),
        ),
    ]
