# Generated by Django 3.2.16 on 2022-12-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_sale_compos_recept_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_compos',
            name='sale_id',
            field=models.ForeignKey(help_text='Выберите дату продажи', on_delete=django.db.models.deletion.CASCADE, related_name='compos', to='main.sale', verbose_name='Продажа'),
        ),
    ]
